server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

spring:
  application:
    name: config-server
  config:
    activate:
      on-profile: native
  cloud:
    config:
      server:
        native:
          search-locations: /home/yanis/IdeaProjects/Eureka/ms-config-properties/{application}/{profile}